name: Copilot Setup Steps

on:
  push:
    branches: [ main ]

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
          cache: true                # NuGet-Caching aktivieren
          cache-dependency-path: |
            Directory.Packages.props
            **/*.csproj
            **/*.fsproj
            **/global.json


      - name: Restore
        run: dotnet restore

      - name: Verify SDK/Runtime
        run: |
          dotnet --info
          dotnet --list-sdks
          dotnet --list-runtimes
